include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LightningPrefs

LightningPrefs_FILES = LSTRootListController.m
LightningPrefs_FRAMEWORKS = UIKit
LightningPrefs_PRIVATE_FRAMEWORKS = Preferences
LightningPrefs_INSTALL_PATH = /Library/PreferenceBundles
LightningPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
